# Generated by Django 5.2 on 2025-04-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="price",
            table="price",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
