# Generated by Django 5.2 on 2025-04-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_category_table_alter_price_table_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Price",
        ),
    ]
