# Generated by Django 5.2 on 2025-04-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_delete_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="provider_id",
        ),
    ]
