# Generated by Django 5.2 on 2025-04-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_provider_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="user_id",
            new_name="user",
        ),
    ]
