# Generated by Django 5.2 on 2025-04-22 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_rename_category_id_product_category_and_more"),
        ("provider", "0002_alter_provider_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="provider.provider",
            ),
            preserve_default=False,
        ),
    ]
