# Generated by Django 5.2 on 2025-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="provider",
            table="provider",
        ),
    ]
